<script lang="ts">
	import { onMount } from 'svelte';
	import { KeyRound, Save } from '@lucide/svelte';
	let license = $state<any>({ status: 'unconfigured', license_key: '', plan: '', licensed_to: '', expires_at: '' });
	let error = $state(''), message = $state('');
	async function load() { const r = await fetch('/api/admin', { cache: 'no-store' }); const p = await r.json(); if (!r.ok) { error = p.error || 'Could not load license'; return; } if (p.license) license = { ...license, ...p.license, expires_at: p.license.expires_at ? p.license.expires_at.slice(0, 10) : '' }; }
	onMount(() => { void load(); });
	async function save() { error = ''; message = ''; const r = await fetch('/api/admin', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action: 'license.save', licenseKey: license.license_key, status: license.status, plan: license.plan, licensedTo: license.licensed_to, expiresAt: license.expires_at ? new Date(`${license.expires_at}T23:59:59Z`).toISOString() : null, metadata: license.metadata ?? {} }) }); const p = await r.json(); if (!r.ok) { error = p.error || 'Could not save license'; return; } message = 'License state saved'; await load(); }
</script>
<div class="mx-auto max-w-4xl space-y-6 p-4 sm:p-6">
	<header><div class="flex items-center gap-2 text-primary"><KeyRound class="size-5" /><p class="text-xs font-semibold uppercase tracking-[0.16em]">Administration</p></div><h1 class="mt-1 text-2xl font-semibold tracking-tight">License</h1><p class="mt-1 text-sm text-muted-foreground">Cloud Base System license state and entitlement metadata.</p></header>
	{#if error}<div class="rounded-lg border border-destructive/40 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</div>{/if}{#if message}<div class="rounded-lg border px-4 py-3 text-sm">{message}</div>{/if}
	<section class="rounded-xl border bg-card p-5 shadow-sm"><div class="grid gap-4 sm:grid-cols-2"><div class="sm:col-span-2"><label class="mb-1.5 block text-sm font-medium">License key</label><input class="h-10 w-full rounded-md border border-input bg-background px-3 font-mono text-sm" bind:value={license.license_key} placeholder="Enter license key" /></div><div><label class="mb-1.5 block text-sm font-medium">Status</label><select class="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" bind:value={license.status}><option value="unconfigured">Unconfigured</option><option value="active">Active</option><option value="expired">Expired</option><option value="invalid">Invalid</option><option value="disabled">Disabled</option></select></div><div><label class="mb-1.5 block text-sm font-medium">Plan</label><input class="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" bind:value={license.plan} placeholder="Plan" /></div><div><label class="mb-1.5 block text-sm font-medium">Licensed to</label><input class="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" bind:value={license.licensed_to} placeholder="Name or organisation" /></div><div><label class="mb-1.5 block text-sm font-medium">Expiry</label><input class="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" type="date" bind:value={license.expires_at} /></div></div><button class="mt-5 inline-flex h-10 items-center gap-2 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground" onclick={save}><Save class="size-4" /> Save license</button></section>
	<div class="rounded-xl border border-dashed p-4 text-sm text-muted-foreground">The cloud license record is now stored independently in Supabase. External entitlement validation from the old desktop backend is a separate porting step and is not being faked here.</div>
</div>
