<script lang="ts">
	import { onMount } from 'svelte';
	import { FileKey, Plus, Trash2 } from '@lucide/svelte';
	import { baseStore } from '$lib/base-store.svelte';
	let permissions = $state<any[]>([]), users = $state<any[]>([]), groups = $state<any[]>([]), error = $state('');
	let pathPrefix = $state(''), principalType = $state('role'), principalId = $state('viewer');
	let canView = $state(true), canCreate = $state(false), canEdit = $state(false), canDelete = $state(false), canManagePermissions = $state(false), inherit = $state(true);
	async function load() { await baseStore.init(); const [panelR, adminR] = await Promise.all([fetch('/api/panel', { cache: 'no-store' }), fetch('/api/admin', { cache: 'no-store' })]); const panel = await panelR.json(), admin = await adminR.json(); if (!panelR.ok) { error = panel.error || 'Could not load permissions'; return; } permissions = panel.permissions ?? []; if (adminR.ok) { users = admin.users ?? []; groups = admin.groups ?? []; } }
	onMount(() => { void load(); });
	const visible = $derived(permissions.filter((p) => p.workspace_id === baseStore.currentWorkspaceId));
	function resetPrincipal() { principalId = principalType === 'role' ? 'viewer' : ''; }
	async function call(action: string, body: Record<string, unknown>) { error = ''; const r = await fetch('/api/panel', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action, ...body }) }); const p = await r.json(); if (!r.ok) { error = p.error || 'Permission update failed'; return false; } await load(); return true; }
	async function addRule() { if (await call('permission.save', { workspaceId: baseStore.currentWorkspaceId, pathPrefix, principalType, principalId, canView, canCreate, canEdit, canDelete, canManagePermissions, inherit })) { pathPrefix = ''; } }
</script>
<div class="mx-auto max-w-6xl space-y-6 p-4 sm:p-6">
	<header><div class="flex items-center gap-2 text-primary"><FileKey class="size-5" /><p class="text-xs font-semibold uppercase tracking-[0.16em]">Administration</p></div><h1 class="mt-1 text-2xl font-semibold tracking-tight">File permissions</h1><p class="mt-1 text-sm text-muted-foreground">Path-level rules for {baseStore.currentWorkspace?.name || 'the selected workspace'}.</p></header>
	{#if error}<div class="rounded-lg border border-destructive/40 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</div>{/if}
	<section class="rounded-xl border bg-card p-4"><h2 class="font-semibold">Add permission rule</h2><div class="mt-4 grid gap-3 md:grid-cols-3"><input class="h-10 rounded-md border border-input bg-background px-3 text-sm" bind:value={pathPrefix} placeholder="Path prefix (blank = workspace root)" /><select class="h-10 rounded-md border border-input bg-background px-3 text-sm" bind:value={principalType} onchange={resetPrincipal}><option value="role">Role</option><option value="user">User</option><option value="group">Group</option></select>{#if principalType === 'role'}<select class="h-10 rounded-md border border-input bg-background px-3 text-sm" bind:value={principalId}><option value="owner">Owner</option><option value="editor">Editor</option><option value="contributor">Contributor</option><option value="viewer">Viewer</option></select>{:else if principalType === 'user'}<select class="h-10 rounded-md border border-input bg-background px-3 text-sm" bind:value={principalId}><option value="">Choose user…</option>{#each users as user}<option value={user.id}>{user.display_name} (@{user.username})</option>{/each}</select>{:else}<select class="h-10 rounded-md border border-input bg-background px-3 text-sm" bind:value={principalId}><option value="">Choose group…</option>{#each groups as group}<option value={group.id}>{group.name}</option>{/each}</select>{/if}</div><div class="mt-4 flex flex-wrap gap-4 text-sm"><label class="flex items-center gap-2"><input type="checkbox" bind:checked={canView} /> View</label><label class="flex items-center gap-2"><input type="checkbox" bind:checked={canCreate} /> Create</label><label class="flex items-center gap-2"><input type="checkbox" bind:checked={canEdit} /> Edit</label><label class="flex items-center gap-2"><input type="checkbox" bind:checked={canDelete} /> Delete</label><label class="flex items-center gap-2"><input type="checkbox" bind:checked={canManagePermissions} /> Manage permissions</label><label class="flex items-center gap-2"><input type="checkbox" bind:checked={inherit} /> Inherit</label></div><button class="mt-4 inline-flex h-10 items-center gap-2 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground disabled:opacity-50" disabled={!baseStore.currentWorkspaceId || !principalId} onclick={addRule}><Plus class="size-4" /> Add rule</button></section>
	<div class="space-y-3">{#each visible as item (item.id)}<article class="rounded-xl border bg-card p-4"><div class="flex items-start justify-between gap-3"><div><div class="flex flex-wrap items-center gap-2"><span class="rounded-full border px-2 py-0.5 text-xs">{item.principal_type}</span><span class="font-mono text-sm">{item.principal_id}</span></div><p class="mt-2 text-sm">Path: <span class="font-mono text-muted-foreground">/{item.path_prefix}</span></p><p class="mt-2 text-xs text-muted-foreground">view {item.can_view ? '✓' : '×'} · create {item.can_create ? '✓' : '×'} · edit {item.can_edit ? '✓' : '×'} · delete {item.can_delete ? '✓' : '×'} · permissions {item.can_manage_permissions ? '✓' : '×'} · inherit {item.inherit ? '✓' : '×'}</p></div><button class="rounded-md border p-2 text-destructive hover:bg-destructive/10" onclick={() => call('permission.delete', { id: item.id })}><Trash2 class="size-4" /></button></div></article>{/each}{#if visible.length === 0}<div class="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">No explicit rules for this workspace yet.</div>{/if}</div>
</div>
