<script lang="ts">
import { onMount } from 'svelte';
import { api,ApiError } from '$lib/api';
import { workspace } from '$lib/workspace.svelte';
import { Badge,Button,Card,CardContent,CardDescription,CardHeader,CardTitle } from '$lib/components/ui';
import { Activity,RefreshCw,ShieldCheck } from '@lucide/svelte';
let policy:any=$state(null),engine:any=$state(null),status:any=$state(null),busy=$state(false),error=$state(''),notice=$state('');
async function load(){try{const a=await api.get<any>('/addons/apex/admin/policy');policy=a.policy;engine=a.engine;if(workspace.currentId)status=await api.get<any>(`/addons/apex/workspaces/${encodeURIComponent(workspace.currentId)}/status`);error='';}catch(e){error=e instanceof ApiError?e.message:'Unable to load APEX';}}
async function save(){busy=true;try{const r=await api.patch<any>('/addons/apex/admin/policy',policy);policy=r.policy;engine=r.engine;notice='APEX cloud policy saved.';}catch(e){error=e instanceof Error?e.message:'Save failed';}finally{busy=false;}}
onMount(async()=>{if(!workspace.workspaces.length)await workspace.load();if(!workspace.currentId&&workspace.workspaces[0])workspace.select(workspace.workspaces[0].id);await load();});
</script>
<svelte:head><title>APEX Master Control · OrbitFS</title></svelte:head>
<div class="mx-auto max-w-6xl space-y-5 p-4 md:p-6">
<div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-xs font-semibold uppercase tracking-[.2em] text-primary">APEX System</p><h1 class="flex items-center gap-2 text-xl font-semibold"><ShieldCheck class="size-5"/>APEX Master Control</h1><p class="text-sm text-muted-foreground">Cloud routing, knowledge-queue policy and engine truth. Filesystem sorting and native conversion are not simulated.</p></div><Button variant="outline" onclick={load}><RefreshCw class="size-4"/>Refresh</Button></div>
{#if error}<div class="rounded-md border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>{/if}{#if notice}<div class="rounded-md border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm">{notice}</div>{/if}
{#if policy}
<div class="grid gap-3 md:grid-cols-3"><Card><CardContent class="p-4"><p class="text-xs text-muted-foreground">Routing engine</p><Badge class="mt-2" variant="warning">{engine?.state||'standby'}</Badge><p class="mt-2 text-xs text-muted-foreground">Ready for request-driven analysis.</p></CardContent></Card><Card><CardContent class="p-4"><p class="text-xs text-muted-foreground">Knowledge queue</p><p class="mt-1 text-2xl font-semibold">{status?.queue?.length||0}</p><p class="text-xs text-muted-foreground">Pending Base approvals</p></CardContent></Card><Card><CardContent class="p-4"><p class="text-xs text-muted-foreground">Native converter</p><Badge class="mt-2" variant="destructive">{engine?.converter?.state||'stopped'}</Badge><p class="mt-2 text-xs text-muted-foreground">No conversion worker attached.</p></CardContent></Card></div>
<Card><CardHeader><CardTitle>Master processing policy</CardTitle><CardDescription>Cloud APEX operates on Library/Memory. Automatic filesystem scans are retired.</CardDescription></CardHeader><CardContent class="space-y-4"><div class="grid gap-3 md:grid-cols-2"><label class="flex items-center justify-between rounded-md border p-3"><span><b>Service mode</b><small class="block text-muted-foreground">Request-driven on Vercel in either mode.</small></span><select class="rounded-md border bg-background px-2 py-1" bind:value={policy.serviceMode}><option value="on_demand">On-demand</option><option value="automatic">Automatic triggers</option></select></label><label class="flex items-center justify-between rounded-md border p-3"><span><b>Block APEX automation</b><small class="block text-muted-foreground">Manual analysis remains available.</small></span><input type="checkbox" bind:checked={policy.blockAutomation}/></label></div><div class="rounded-md border bg-muted/20 p-3 text-sm"><b>Filesystem scanning:</b> disabled in cloud. <b>Sorter destination:</b> Library / Memory / Profiles through approvals.</div><div class="flex justify-end"><Button onclick={save} disabled={busy}><Activity class="size-4"/>Save policy</Button></div></CardContent></Card>
<Card><CardHeader><CardTitle>Recent APEX approval activity</CardTitle><CardDescription>APEX suggestions are retained in the Base approval history.</CardDescription></CardHeader><CardContent class="space-y-2">{#if !(status?.queue?.length||status?.history?.length)}<p class="text-sm text-muted-foreground">No APEX requests yet.</p>{/if}{#each [...(status?.queue||[]),...(status?.history||[]).slice(0,20)] as item}<div class="rounded-md border p-3"><div class="flex items-center justify-between gap-2"><strong>{item.summary||'APEX request'}</strong><Badge variant="outline">{item.status}</Badge></div><p class="mt-1 text-xs text-muted-foreground">{item.reason||''}</p></div>{/each}</CardContent></Card>
{/if}</div>