<script lang="ts">
	import { onMount } from 'svelte';
	import { Plus, Trash2, UserPlus, UsersRound } from '@lucide/svelte';
	let users = $state<any[]>([]), groups = $state<any[]>([]), members = $state<any[]>([]);
	let name = $state(''), description = $state(''), error = $state('');
	async function load() { const r = await fetch('/api/admin', { cache: 'no-store' }); const p = await r.json(); if (!r.ok) { error = p.error || 'Could not load groups'; return; } users = p.users ?? []; groups = p.groups ?? []; members = p.groupMembers ?? []; }
	onMount(() => { void load(); });
	async function call(action: string, body: Record<string, unknown>) { error = ''; const r = await fetch('/api/admin', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action, ...body }) }); const p = await r.json(); if (!r.ok) { error = p.error || 'Update failed'; return false; } await load(); return true; }
	async function createGroup() { if (await call('group.create', { name, description })) { name = ''; description = ''; } }
	function groupMembers(groupId: string) { const ids = new Set(members.filter((m) => m.group_id === groupId).map((m) => m.user_id)); return users.filter((u) => ids.has(u.id)); }
	function availableUsers(groupId: string) { const ids = new Set(members.filter((m) => m.group_id === groupId).map((m) => m.user_id)); return users.filter((u) => !ids.has(u.id)); }
</script>
<div class="mx-auto max-w-6xl space-y-6 p-4 sm:p-6">
	<header><div class="flex items-center gap-2 text-primary"><UsersRound class="size-5" /><p class="text-xs font-semibold uppercase tracking-[0.16em]">Administration</p></div><h1 class="mt-1 text-2xl font-semibold tracking-tight">User groups</h1><p class="mt-1 text-sm text-muted-foreground">Create groups and assign registered OrbitFS users.</p></header>
	{#if error}<div class="rounded-lg border border-destructive/40 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</div>{/if}
	<section class="rounded-xl border bg-card p-4"><div class="grid gap-3 sm:grid-cols-[1fr_1.5fr_auto]"><input class="h-10 rounded-md border border-input bg-background px-3 text-sm" bind:value={name} placeholder="Group name" /><input class="h-10 rounded-md border border-input bg-background px-3 text-sm" bind:value={description} placeholder="Description" /><button class="inline-flex h-10 items-center justify-center gap-2 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground disabled:opacity-50" disabled={!name.trim()} onclick={createGroup}><Plus class="size-4" /> Create group</button></div></section>
	<div class="grid gap-4 lg:grid-cols-2">{#each groups as group (group.id)}<article class="rounded-xl border bg-card p-4 shadow-sm"><div class="flex items-start justify-between gap-3"><div><h2 class="font-semibold">{group.name}</h2><p class="mt-1 text-sm text-muted-foreground">{group.description || 'No description'}</p></div><button class="rounded-md border p-2 text-destructive hover:bg-destructive/10" onclick={() => call('group.delete', { id: group.id })}><Trash2 class="size-4" /></button></div><div class="mt-4 space-y-2"><p class="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Members</p>{#each groupMembers(group.id) as user}<div class="flex items-center justify-between rounded-lg border px-3 py-2 text-sm"><span>{user.display_name} <span class="text-muted-foreground">@{user.username}</span></span><button class="text-xs text-destructive hover:underline" onclick={() => call('group.member.remove', { groupId: group.id, userId: user.id })}>Remove</button></div>{/each}{#if groupMembers(group.id).length === 0}<p class="text-sm text-muted-foreground">No members yet.</p>{/if}</div>{#if availableUsers(group.id).length}<div class="mt-3"><select class="h-9 w-full rounded-md border border-input bg-background px-3 text-sm" onchange={(e) => { const id = e.currentTarget.value; if (id) { void call('group.member.add', { groupId: group.id, userId: id }); e.currentTarget.value = ''; } }}><option value="">Add member…</option>{#each availableUsers(group.id) as user}<option value={user.id}>{user.display_name} (@{user.username})</option>{/each}</select></div>{/if}</article>{/each}</div>
</div>
