<script lang="ts">
	import { onMount } from 'svelte';
	import { Bell, Send } from '@lucide/svelte';
	let users = $state<any[]>([]), userId = $state(''), title = $state(''), body = $state(''), level = $state('info'), error = $state(''), message = $state('');
	onMount(async () => { const r = await fetch('/api/admin', { cache: 'no-store' }); const p = await r.json(); if (r.ok) users = p.users ?? []; else error = p.error || 'Could not load users'; });
	async function send() { error = ''; message = ''; const r = await fetch('/api/admin', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action: 'notification.create', userId, title, body, level }) }); const p = await r.json(); if (!r.ok) { error = p.error || 'Could not send notification'; return; } message = 'Notification sent'; title = ''; body = ''; }
</script>
<div class="mx-auto max-w-3xl space-y-6 p-4 sm:p-6">
	<header><div class="flex items-center gap-2 text-primary"><Bell class="size-5" /><p class="text-xs font-semibold uppercase tracking-[0.16em]">Administration</p></div><h1 class="mt-1 text-2xl font-semibold tracking-tight">System messages</h1><p class="mt-1 text-sm text-muted-foreground">Send notifications to one user or everyone.</p></header>
	{#if error}<div class="rounded-lg border border-destructive/40 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</div>{/if}{#if message}<div class="rounded-lg border px-4 py-3 text-sm">{message}</div>{/if}
	<section class="space-y-4 rounded-xl border bg-card p-5"><div><label class="mb-1.5 block text-sm font-medium">Recipient</label><select class="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" bind:value={userId}><option value="">Everyone</option>{#each users as user}<option value={user.id}>{user.display_name} (@{user.username})</option>{/each}</select></div><div class="grid gap-4 sm:grid-cols-[1fr_160px]"><div><label class="mb-1.5 block text-sm font-medium">Title</label><input class="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" bind:value={title} /></div><div><label class="mb-1.5 block text-sm font-medium">Level</label><select class="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" bind:value={level}><option value="info">Info</option><option value="success">Success</option><option value="warning">Warning</option><option value="error">Error</option></select></div></div><div><label class="mb-1.5 block text-sm font-medium">Message</label><textarea class="min-h-40 w-full rounded-md border border-input bg-background p-3 text-sm" bind:value={body}></textarea></div><button class="inline-flex h-10 items-center gap-2 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground disabled:opacity-50" disabled={!title.trim()} onclick={send}><Send class="size-4" /> Send notification</button></section>
</div>
