<script lang="ts">
	import { api, ApiError } from '$lib/api';
	import { Card, CardHeader, CardTitle, CardDescription, CardContent, Button, Input } from '$lib/components/ui';
	import { CloudCog, Database, Globe, HardDriveDownload, LoaderCircle, Save, Settings2 } from '@lucide/svelte';
	type RuntimeConfig = { config: Record<string, Record<string, unknown>> };
	let runtime=$state<RuntimeConfig['config']|null>(null), runtimeLoading=$state(true), runtimeError=$state('');
	async function loadRuntime(){runtimeLoading=true;runtimeError='';try{runtime=(await api.get<RuntimeConfig>('/config/runtime')).config;}catch(err){runtimeError=err instanceof ApiError?err.message:'Failed to load runtime config';}finally{runtimeLoading=false;}}
	loadRuntime();
	let driveClientId=$state(''),driveLoading=$state(true),driveSaving=$state(false),driveError=$state(''),driveSaved=$state(false);
	async function loadDrive(){driveLoading=true;driveError='';try{driveClientId=(await api.get<{clientId:string|null}>('/drive-config')).clientId??'';}catch(err){driveError=err instanceof ApiError?err.message:'Failed to load Drive config';}finally{driveLoading=false;}}
	loadDrive();
	async function saveDrive(e:Event){e.preventDefault();driveSaving=true;driveError='';driveSaved=false;try{await api.patch('/system/drive-config',{clientId:driveClientId.trim(),enabled:Boolean(driveClientId.trim())});driveSaved=true;}catch(err){driveError=err instanceof ApiError?err.message:'Save failed';}finally{driveSaving=false;}}
</script>

<div class="mx-auto max-w-4xl space-y-6 p-4 md:p-6">
	<div><h1 class="flex items-center gap-2 text-xl font-semibold tracking-tight"><Settings2 class="size-5 text-muted-foreground" />Configuration</h1><p class="text-sm text-muted-foreground">Cloud deployment state and Panel-managed integrations for the Vercel/Supabase edition of OrbitFS.</p></div>
	<Card><CardHeader><CardTitle class="flex items-center gap-2"><CloudCog class="size-4" />Cloud runtime</CardTitle><CardDescription>Deployment infrastructure is read-only here because Vercel and Supabase own it.</CardDescription></CardHeader><CardContent>{#if runtimeLoading}<div class="flex items-center gap-2 text-sm text-muted-foreground"><LoaderCircle class="size-4 animate-spin" />Loading…</div>{:else if runtimeError}<p class="text-sm text-destructive">{runtimeError}</p>{:else if runtime}<div class="grid gap-2 sm:grid-cols-2">{#each Object.entries(runtime) as [section,values] (section)}<div class="rounded-lg border bg-background/40 p-3"><div class="mb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">{section}</div>{#each Object.entries(values??{}) as [key,value] (key)}<div class="flex justify-between gap-3 py-0.5 text-xs"><span class="text-muted-foreground">{key}</span><span class="max-w-[60%] break-all text-right font-mono">{String(value)}</span></div>{/each}</div>{/each}</div>{/if}</CardContent></Card>
	<div class="grid gap-3 md:grid-cols-3">
		<a href="/admin/config/install" class="rounded-lg border bg-card p-4 text-sm hover:bg-accent/40"><CloudCog class="mb-2 size-5 text-primary" /><p class="font-medium">Deployment</p><p class="mt-1 text-muted-foreground">Vercel runtime, Supabase backing services and connectivity checks.</p></a>
		<a href="/admin/config/paths" class="rounded-lg border bg-card p-4 text-sm hover:bg-accent/40"><Database class="mb-2 size-5 text-primary" /><p class="font-medium">Storage mapping</p><p class="mt-1 text-muted-foreground">Read-only database and object-storage locations.</p></a>
		<a href="/admin/config/ports-urls" class="rounded-lg border bg-card p-4 text-sm hover:bg-accent/40"><Globe class="mb-2 size-5 text-primary" /><p class="font-medium">Cloud endpoints</p><p class="mt-1 text-muted-foreground">Current public Panel, API and licensing endpoints.</p></a>
	</div>
	<Card><CardHeader><CardTitle class="flex items-center gap-2"><HardDriveDownload class="size-4" />Google Drive</CardTitle><CardDescription>Optional Panel integration. This is a real editable application setting, unlike deployment-managed infrastructure.</CardDescription></CardHeader><CardContent>{#if driveLoading}<div class="flex items-center gap-2 text-sm text-muted-foreground"><LoaderCircle class="size-4 animate-spin" />Loading…</div>{:else}<form class="flex flex-wrap items-end gap-2" onsubmit={saveDrive}><div class="min-w-64 flex-1 space-y-1.5"><label for="drive-client-id" class="text-sm font-medium">OAuth client ID</label><Input id="drive-client-id" bind:value={driveClientId} placeholder="xxxxx.apps.googleusercontent.com" /></div><Button type="submit" size="sm" disabled={driveSaving}>{#if driveSaving}<LoaderCircle class="size-4 animate-spin" />{:else}<Save class="size-4" />{/if}Save</Button></form>{#if driveError}<p class="mt-2 text-sm text-destructive">{driveError}</p>{/if}{#if driveSaved}<p class="mt-2 text-sm text-success">Saved.</p>{/if}{/if}</CardContent></Card>
</div>