<script lang="ts">
	import { onMount } from 'svelte';
	import { Plus, Save, Settings } from '@lucide/svelte';
	let settings = $state<any[]>([]), key = $state(''), valueText = $state('{}'), error = $state(''), message = $state('');
	async function load() { const r = await fetch('/api/admin', { cache: 'no-store' }); const p = await r.json(); if (!r.ok) { error = p.error || 'Could not load settings'; return; } settings = p.settings ?? []; }
	onMount(() => { void load(); });
	async function save(scopeType: string, scopeId: string, settingKey: string, value: unknown) { error = ''; message = ''; const r = await fetch('/api/admin', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action: 'setting.save', scopeType, scopeId, key: settingKey, value }) }); const p = await r.json(); if (!r.ok) { error = p.error || 'Save failed'; return false; } message = 'Saved'; await load(); return true; }
	async function create() { try { const value = JSON.parse(valueText); if (await save('global', '', key.trim(), value)) { key = ''; valueText = '{}'; } } catch { error = 'Value must be valid JSON'; } }
</script>
<div class="mx-auto max-w-5xl space-y-6 p-4 sm:p-6">
	<header><div class="flex items-center gap-2 text-primary"><Settings class="size-5" /><p class="text-xs font-semibold uppercase tracking-[0.16em]">Administration</p></div><h1 class="mt-1 text-2xl font-semibold tracking-tight">Base System settings</h1><p class="mt-1 text-sm text-muted-foreground">Cloud-safe global, workspace and user configuration stored in Supabase.</p></header>
	{#if error}<div class="rounded-lg border border-destructive/40 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</div>{/if}{#if message}<div class="rounded-lg border px-4 py-3 text-sm">{message}</div>{/if}
	<section class="rounded-xl border bg-card p-4"><h2 class="font-semibold">Add global setting</h2><div class="mt-3 grid gap-3 sm:grid-cols-[1fr_1.5fr_auto]"><input class="h-10 rounded-md border border-input bg-background px-3 text-sm" bind:value={key} placeholder="registration.mode" /><input class="h-10 rounded-md border border-input bg-background px-3 font-mono text-sm" bind:value={valueText} placeholder='"open" or {"enabled":true}' /><button class="inline-flex h-10 items-center justify-center gap-2 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground disabled:opacity-50" disabled={!key.trim()} onclick={create}><Plus class="size-4" /> Add</button></div></section>
	<div class="space-y-3">{#each settings as item (item.id)}<article class="rounded-xl border bg-card p-4"><div class="flex flex-wrap items-start justify-between gap-3"><div><div class="flex items-center gap-2"><span class="rounded-full border px-2 py-0.5 text-xs">{item.scope_type}</span><h2 class="font-mono text-sm font-semibold">{item.key}</h2></div><p class="mt-1 text-xs text-muted-foreground">Scope ID: {item.scope_id || 'global'}</p></div><button class="inline-flex h-9 items-center gap-2 rounded-md border px-3 text-sm hover:bg-muted" onclick={() => save(item.scope_type, item.scope_id, item.key, item.value)}><Save class="size-4" /> Save</button></div><textarea class="mt-3 min-h-24 w-full rounded-md border border-input bg-background p-3 font-mono text-xs" value={JSON.stringify(item.value, null, 2)} onchange={(e) => { try { item.value = JSON.parse(e.currentTarget.value); error = ''; } catch { error = `Invalid JSON for ${item.key}`; } }}></textarea></article>{/each}{#if settings.length === 0}<div class="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">No custom settings yet.</div>{/if}</div>
</div>
