<script lang="ts">
import { onMount } from 'svelte';
import { api,ApiError } from '$lib/api';
import { Badge,Button,Card,CardContent,CardDescription,CardHeader,CardTitle,Input } from '$lib/components/ui';
import { Activity,RefreshCw,Save,ShieldCheck } from '@lucide/svelte';
let settings:any=$state(null),engine:any=$state(null),busy=$state(false),error=$state(''),notice=$state('');
async function load(){try{const [r,e]=await Promise.all([api.get<any>('/addons/studio/admin/settings'),api.get<any>('/addons/studio/admin/engine')]);settings=r.settings;engine=e.engine;error='';}catch(e){error=e instanceof ApiError?e.message:'Unable to load advanced Studio settings';}}
async function save(){busy=true;try{const r=await api.patch<any>('/addons/studio/admin/settings',{routingEnabled:settings.routingEnabled,routingAutoAnalyzeCreate:settings.routingAutoAnalyzeCreate,routingAutoAnalyzeUpdate:settings.routingAutoAnalyzeUpdate,routingUseApexSignals:settings.routingUseApexSignals,routingMinConfidence:settings.routingMinConfidence,routingProfileConfidence:settings.routingProfileConfidence,routingIncidentConfidence:settings.routingIncidentConfidence,routingTimelineConfidence:settings.routingTimelineConfidence,routingMaxSuggestions:settings.routingMaxSuggestions,routingMaxCharacters:settings.routingMaxCharacters,analysisPolicy:settings.analysisPolicy});settings=r.settings;notice='Advanced Studio settings saved.';}catch(e){error=e instanceof Error?e.message:'Save failed';}finally{busy=false;}}
onMount(load);
</script>
<svelte:head><title>Advanced Studio Engine · OrbitFS</title></svelte:head>
<div class="mx-auto max-w-6xl space-y-5 p-4 md:p-6"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-xs font-semibold uppercase tracking-[.2em] text-primary">OrbitFS Studio</p><h1 class="flex items-center gap-2 text-xl font-semibold"><Activity class="size-5"/>Advanced Engine</h1><p class="text-sm text-muted-foreground">Routing, analysis policy, providers and safeguards. Vercel uses request-driven standby instead of a resident Windows service.</p></div><div class="flex gap-2"><a class="rounded-md border px-3 py-2 text-sm hover:bg-accent" href="/admin/studio/settings">System Settings</a><Button variant="outline" onclick={load}><RefreshCw class="size-4"/>Refresh</Button></div></div>
{#if error}<div class="rounded-md border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>{/if}{#if notice}<div class="rounded-md border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm">{notice}</div>{/if}
{#if settings}
<Card><CardHeader><CardTitle>Cloud engine state</CardTitle><CardDescription>Standby means configured and ready. Running is only used for actual request work; there is no resident service to start or stop.</CardDescription></CardHeader><CardContent><div class="grid gap-2 sm:grid-cols-3"><div class="rounded-md border p-3"><p class="text-xs text-muted-foreground">State</p><p class="font-semibold">{engine?.state||'standby'}</p></div><div class="rounded-md border p-3"><p class="text-xs text-muted-foreground">Mode</p><p class="font-semibold">Serverless</p></div><div class="rounded-md border p-3"><p class="text-xs text-muted-foreground">Database</p><p class="font-semibold">{engine?.database?'Connected':'Unavailable'}</p></div></div></CardContent></Card>
<Card><CardHeader><CardTitle>Routing engine</CardTitle><CardDescription>Deterministic routing; semantic provider is not configured and is not presented as AI.</CardDescription></CardHeader><CardContent class="space-y-4"><div class="grid gap-3 md:grid-cols-2">{#each [['Enable routing','routingEnabled'],['Use APEX signals','routingUseApexSignals'],['Analyse new entries','routingAutoAnalyzeCreate'],['Analyse edits','routingAutoAnalyzeUpdate']] as x}<label class="flex items-center justify-between rounded-md border p-3"><b>{x[0]}</b><input type="checkbox" bind:checked={settings[x[1]]}/></label>{/each}</div><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{#each [['Minimum','routingMinConfidence'],['Profile','routingProfileConfidence'],['Incident','routingIncidentConfidence'],['Timeline','routingTimelineConfidence']] as x}<div><label class="text-sm font-medium">{x[0]}</label><Input type="number" min="0" max="1" step="0.01" bind:value={settings[x[1]]}/></div>{/each}<div><label class="text-sm font-medium">Max suggestions</label><Input type="number" min="1" max="20" bind:value={settings.routingMaxSuggestions}/></div><div><label class="text-sm font-medium">Character budget</label><Input type="number" bind:value={settings.routingMaxCharacters}/></div></div></CardContent></Card>
<Card><CardHeader><CardTitle>Knowledge-analysis policy</CardTitle><CardDescription>Controls duplicate/update/link/review/conflict/merge decisions. Findings still require Base approval before authoritative writes.</CardDescription></CardHeader><CardContent class="space-y-4"><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{#each [['Candidate floor','candidateFloor'],['Review','reviewThreshold'],['Conflict','conflictThreshold'],['Merge','mergeThreshold'],['Update','updateThreshold'],['Add confidence','addConfidence']] as x}<div><label class="text-sm font-medium">{x[0]}</label><Input type="number" min="0" max="1" step="0.01" bind:value={settings.analysisPolicy[x[1]]}/></div>{/each}</div><div class="grid gap-3 md:grid-cols-3">{#each [['Detect conflicts','detectConflicts'],['Detect merge candidates','detectMerges'],['Use structure signal','useStructureSignal']] as x}<label class="flex items-center justify-between rounded-md border p-3"><b>{x[0]}</b><input type="checkbox" bind:checked={settings.analysisPolicy[x[1]]}/></label>{/each}</div><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{#each [['Content','content'],['Title','title'],['Date','date'],['Type','type'],['Entities','entities'],['Structure','structure']] as x}<div><label class="text-sm font-medium">{x[0]} weight</label><Input type="number" min="0" max="2" step="0.01" bind:value={settings.analysisPolicy.weights[x[1]]}/></div>{/each}</div><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><div><label class="text-sm font-medium">Candidates / record</label><Input type="number" bind:value={settings.analysisPolicy.maxCandidatesPerRecord}/></div><div><label class="text-sm font-medium">Max sources / run</label><Input type="number" bind:value={settings.analysisPolicy.limits.maxSourcesPerRun}/></div><div><label class="text-sm font-medium">Max records / run</label><Input type="number" bind:value={settings.analysisPolicy.limits.maxRecordsPerRun}/></div><div><label class="text-sm font-medium">Queue depth</label><Input type="number" bind:value={settings.analysisPolicy.limits.queueDepthLimit}/></div><div><label class="text-sm font-medium">Stuck task minutes</label><Input type="number" bind:value={settings.analysisPolicy.limits.stuckTaskMinutes}/></div></div><div class="grid gap-3 md:grid-cols-4">{#each [['Providers by default','enabledByDefault'],['APEX provider','apex'],['MCP provider','mcp'],['Other add-on signals','other']] as x}<label class="flex items-center justify-between rounded-md border p-3"><b>{x[0]}</b><input type="checkbox" bind:checked={settings.analysisPolicy.providers[x[1]]}/></label>{/each}</div></CardContent></Card>
<Card><CardHeader><CardTitle class="flex items-center gap-2"><ShieldCheck class="size-4"/>Locked safeguards</CardTitle></CardHeader><CardContent class="grid gap-2 sm:grid-cols-2"><div class="flex justify-between rounded-md border p-3"><span>Library approval before authoritative writes</span><Badge variant="success">Always</Badge></div><div class="flex justify-between rounded-md border p-3"><span>Stale-content validation</span><Badge variant="success">Always</Badge></div><div class="flex justify-between rounded-md border p-3"><span>Write verification + rollback</span><Badge variant="success">Always</Badge></div><div class="flex justify-between rounded-md border p-3"><span>Filesystem / direct binary mutation</span><Badge>Disabled</Badge></div></CardContent></Card>
<div class="flex justify-end"><Button onclick={save} disabled={busy}><Save class="size-4"/>Save advanced settings</Button></div>
{/if}</div>