export const ORBITFS_WIDGET_URI = 'ui://orbitfs/dashboard-v1.html';

export const ORBITFS_WIDGET_HTML = `<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<style>
:root{font-family:system-ui,sans-serif;color-scheme:light dark}body{margin:0;padding:14px;background:transparent;color:CanvasText}.card{border:1px solid color-mix(in srgb,CanvasText 16%,transparent);border-radius:16px;padding:16px;background:Canvas}.top{display:flex;align-items:center;justify-content:space-between;gap:12px}.brand{font-size:18px;font-weight:750}.pill{font-size:12px;border:1px solid color-mix(in srgb,CanvasText 18%,transparent);border-radius:999px;padding:5px 9px}.muted{opacity:.68;font-size:13px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin-top:14px}.item{border:1px solid color-mix(in srgb,CanvasText 12%,transparent);border-radius:11px;padding:10px}.item b{display:block;font-size:13px}.item span{font-size:12px;opacity:.7}.actions{display:flex;gap:8px;margin-top:14px;flex-wrap:wrap}.workspaces{margin-top:12px;font-size:12px;opacity:.78}button,a{font:inherit;border-radius:9px;padding:8px 11px;border:1px solid color-mix(in srgb,CanvasText 18%,transparent);background:transparent;color:inherit;text-decoration:none;cursor:pointer}.primary{background:CanvasText;color:Canvas}
</style></head><body><main class="card"><div class="top"><div><div class="brand">OrbitFS</div><div class="muted" id="identity">Connected through MCP</div></div><span class="pill" id="status">Online</span></div>
<div class="grid"><div class="item"><b>Workspace context</b><span>Profiles, projects and startup context</span></div><div class="item"><b>Knowledge</b><span>Library and context bundles</span></div><div class="item"><b>Projects</b><span>MCP project context and presets</span></div><div class="item"><b>OAuth</b><span>Authenticated OrbitFS account</span></div></div>
<div class="workspaces" id="workspaces">Loading accessible workspaces...</div><div class="actions"><button class="primary" id="ask">Use my OrbitFS context</button><a id="open" href="https://orbitfsproject.vercel.app" target="_blank" rel="noreferrer">Open OrbitFS Project</a></div></main>
<script>
function apply(data){if(!data)return;document.getElementById('status').textContent=data.status||'Online';if(data.user)document.getElementById('identity').textContent='Connected as '+data.user;const ws=Array.isArray(data.workspaces)?data.workspaces:[];document.getElementById('workspaces').textContent=ws.length?('Workspaces: '+ws.map(w=>w.name||w.slug||w.id).join(', ')):'No accessible workspaces';}
window.addEventListener('message',(event)=>{const m=event.data;if(m&&m.method==='ui/notifications/tool-result')apply(m.params?.structuredContent||m.params?.content?.structuredContent);});
if(window.openai){apply(window.openai.toolOutput);document.getElementById('ask').onclick=()=>window.openai.sendFollowUpMessage?.({prompt:'Use my OrbitFS context and show me what is currently available.'});document.getElementById('open').onclick=(e)=>{if(window.openai.openExternal){e.preventDefault();window.openai.openExternal({href:'https://orbitfsproject.vercel.app'});}};}
</script></body></html>`;
