import { getSupabaseAdmin } from '$lib/server/supabase';
import type { OrbitUser } from '$lib/server/auth';
import { visibleWorkspaces } from '$lib/server/workspaces';
import { requireMcpWorkspace, listMcpProjects, listContextBundles, getContextBundle, getStartup, getPresets, getPresetMetadata, getPresetBundles } from '$lib/server/mcp-workspace-state';
import { findEntry, listEntries, readEntryBytes, writeFileBytes, createFolder, moveEntry, purgeEntry, requireCapability, normalizePath } from '$lib/server/base-compat';
import { profileCatalog, profileKnowledgeProjection, updateProfile } from '$lib/server/workspace-profiles.js';

const now=()=>new Date().toISOString();
const text=(v:unknown)=>String(v??'');
export type RuntimeIdentity={user:OrbitUser;clientId:string;contextKey:string};

async function contextRow(identity:RuntimeIdentity,workspaceId:string){
 const db=getSupabaseAdmin(); const r=await db.from('mcp_active_contexts').select('receipt').eq('user_id',identity.user.id).eq('client_id',identity.clientId).eq('workspace_id',workspaceId).eq('context_key',identity.contextKey).maybeSingle(); if(r.error)throw r.error; return r.data?.receipt||null;
}
async function saveContext(identity:RuntimeIdentity,workspaceId:string,receipt:any){
 const db=getSupabaseAdmin(); const r=await db.from('mcp_active_contexts').upsert({user_id:identity.user.id,client_id:identity.clientId,workspace_id:workspaceId,context_key:identity.contextKey,receipt,updated_at:now()},{onConflict:'user_id,client_id,workspace_id,context_key'}); if(r.error)throw r.error; return receipt;
}
export async function clearActiveContext(identity:RuntimeIdentity,workspaceId:string){
 const db=getSupabaseAdmin(); const r=await db.from('mcp_active_contexts').delete().eq('user_id',identity.user.id).eq('client_id',identity.clientId).eq('workspace_id',workspaceId).eq('context_key',identity.contextKey); if(r.error)throw r.error; return null;
}
function blankReceipt(workspaceId:string,clientId:string){return {contextId:`ctx-${crypto.randomUUID()}`,clientId,workspaceId,startedAt:now(),completedAt:now(),files:[],errors:[],bundles:[],charactersTransferred:0,failedCount:0,transferredCount:0};}
function recalc(receipt:any){receipt.files=receipt.files||[];receipt.errors=receipt.errors||[];receipt.charactersTransferred=receipt.files.reduce((n:number,f:any)=>n+Number(f.characters||0),0);receipt.transferredCount=receipt.files.length;receipt.failedCount=receipt.errors.length;receipt.completedAt=now();return receipt;}
export async function activeContext(identity:RuntimeIdentity,workspaceId:string){return await contextRow(identity,workspaceId)||null;}
async function appendItems(identity:RuntimeIdentity,workspaceId:string,items:any[],extra:any={}){const receipt=await contextRow(identity,workspaceId)||blankReceipt(workspaceId,identity.clientId);const map=new Map((receipt.files||[]).map((f:any)=>[String(f.path).toLowerCase(),f]));for(const item of items)map.set(String(item.path).toLowerCase(),item);receipt.files=[...map.values()];Object.assign(receipt,extra);return saveContext(identity,workspaceId,recalc(receipt));}

export async function listWorkspaceEntries(identity:RuntimeIdentity,workspaceId:string,path=''){
 await requireMcpWorkspace(identity.user,workspaceId); const rows=await listEntries(workspaceId,path); return rows.map((r:any)=>({...r,type:r.type==='dir'?'folder':'file',path:normalizePath([path,r.name].filter(Boolean).join('/'))}));
}
export async function readFile(identity:RuntimeIdentity,workspaceId:string,path:string,output='auto',maxBytes=20*1024*1024,maxCharacters=20000){
 await requireMcpWorkspace(identity.user,workspaceId); await requireCapability(identity.user,workspaceId,path,'read'); const entry=await findEntry(workspaceId,path); if(!entry||entry.kind!=='file')throw Object.assign(new Error('File not found'),{status:404}); const bytes=await readEntryBytes(entry); if(bytes.length>maxBytes)throw Object.assign(new Error('File exceeds requested maximum size'),{status:413}); const mimeType=entry.mime_type||'application/octet-stream'; const isText=output!=='base64'&&(mimeType.startsWith('text/')||/json|xml|javascript|markdown/.test(mimeType)||entry.content_text); return isText?{encoding:'text',document:{content:bytes.toString('utf8').slice(0,maxCharacters)},metadata:{mimeType,bytes:bytes.length,modifiedAt:entry.updated_at}}:{encoding:'base64',data:bytes.toString('base64'),metadata:{mimeType,bytes:bytes.length,modifiedAt:entry.updated_at}};
}
export async function loadFile(identity:RuntimeIdentity,workspaceId:string,path:string,meta:any={}){const data=await readFile(identity,workspaceId,path,'auto',20*1024*1024,500000);const content=data.encoding==='text'?data.document.content:'';const item={path:normalizePath(path),source:meta.source||'workspace',bundleId:meta.bundleId||null,bundleName:meta.bundleName||null,characters:content.length,mimeType:data.metadata.mimeType,loadedAt:now()};const receipt=await appendItems(identity,workspaceId,[item]);return {item,receipt,content};}
export async function loadFolder(identity:RuntimeIdentity,workspaceId:string,path:string,maxFiles=50,maxCharacters=500000){await requireMcpWorkspace(identity.user,workspaceId);const db=getSupabaseAdmin();const clean=normalizePath(path);const r=await db.from('orbitfs_files').select('path,kind').eq('workspace_id',workspaceId).is('deleted_at',null);if(r.error)throw r.error;const paths=(r.data||[]).filter((x:any)=>x.kind==='file'&&(x.path===clean||x.path.startsWith(clean+'/'))).slice(0,maxFiles).map((x:any)=>x.path);const loaded=[];let chars=0;for(const p of paths){try{const x=await loadFile(identity,workspaceId,p);loaded.push(x.item);chars+=x.item.characters;if(chars>=maxCharacters)break;}catch{}}return {loaded,receipt:await activeContext(identity,workspaceId)};}
export async function listLibraryItems(identity:RuntimeIdentity,workspaceId:string){await requireMcpWorkspace(identity.user,workspaceId);const db=getSupabaseAdmin();const r=await db.from('orbitfs_library_state').select('state').eq('workspace_id',workspaceId).maybeSingle();if(r.error)throw r.error;const state=r.data?.state||{};return (state.items||[]).map((item:any)=>({id:item.id,name:item.name,kind:item.kind,category:item.category||'',lifecycle:item.lifecycle||'unclassified',roles:item.roles||[],source:item.source||null,updatedAt:item.updatedAt||null}));}
export async function loadKnowledgeItem(identity:RuntimeIdentity,workspaceId:string,itemId:string,meta:any={}){await requireMcpWorkspace(identity.user,workspaceId);const db=getSupabaseAdmin();const r=await db.from('orbitfs_library_state').select('state').eq('workspace_id',workspaceId).maybeSingle();if(r.error)throw r.error;const state=r.data?.state||{},item=(state.items||[]).find((x:any)=>String(x.id)===String(itemId));if(!item)throw Object.assign(new Error('Library knowledge item not found'),{status:404});const lifecycle=String(item.lifecycle||'unclassified');if(lifecycle==='deprecated')throw Object.assign(new Error('Deprecated Library items cannot be loaded into active context'),{status:409,code:'LIBRARY_DEPRECATED'});const mode=['summary','smart','full'].includes(String(meta.loadMode))?String(meta.loadMode):'smart';let content='';if(item.source?.provider==='library.native')content=String(item.content||'');else{const sections=(state.sections||[]).filter((x:any)=>String(x.itemId)===String(item.id));content=sections.map((x:any)=>String(mode==='summary'?(x.preview||x.content||''):(x.content||x.preview||''))).filter(Boolean).join('\n\n');}if(mode==='summary')content=content.slice(0,4000);else if(mode==='smart')content=content.slice(0,120000);const warning=({old:'Historical/old Library source.',archived:'Archived Library source.',reference_only:'Reference-only Library source.',draft:'Draft Library source; not authoritative.'} as any)[lifecycle]||null;const ctxItem={path:`Library/${item.id}`,libraryItemId:item.id,libraryItemName:item.name,source:'knowledge',lifecycle,warning,bundleId:meta.bundleId||null,bundleName:meta.bundleName||null,loadMode:mode,characters:content.length,loadedAt:now()};const receipt=await appendItems(identity,workspaceId,[ctxItem]);return {item,contextItem:ctxItem,receipt,content,warning};}
export async function removeContextFile(identity:RuntimeIdentity,workspaceId:string,path:string){const receipt=await contextRow(identity,workspaceId)||blankReceipt(workspaceId,identity.clientId);const target=normalizePath(path).toLowerCase();receipt.files=(receipt.files||[]).filter((f:any)=>String(f.path||'').toLowerCase()!==target);return saveContext(identity,workspaceId,recalc(receipt));}
export async function loadBundle(identity:RuntimeIdentity,workspaceId:string,bundleId:string){await requireMcpWorkspace(identity.user,workspaceId);const bundle=await getContextBundle(workspaceId,bundleId);const loaded:any[]=[];for(const e of bundle.entries||[]){try{if(e.attachmentType==='profile'&&e.profileId){const x=await loadProfile(identity,workspaceId,e.profileId,'standard',{bundleId,bundleName:bundle.name});loaded.push(x.item);}else if(e.attachmentType==='knowledge'&&e.knowledgeItemId){const x=await loadKnowledgeItem(identity,workspaceId,e.knowledgeItemId,{bundleId,bundleName:bundle.name,loadMode:e.loadMode});loaded.push(x.contextItem);}else if(e.type==='folder'){const x=await loadFolder(identity,workspaceId,e.path,100,1000000);loaded.push(...x.loaded);}else{const x=await loadFile(identity,workspaceId,e.path,{source:'bundle',bundleId,bundleName:bundle.name});loaded.push(x.item);}}catch{if(e.required)throw new Error(`Required bundle item could not be loaded: ${e.path||e.profileName||e.profileId||e.knowledgeItemName||e.knowledgeItemId}`);}}const receipt=await contextRow(identity,workspaceId)||blankReceipt(workspaceId,identity.clientId);const bundles=(receipt.bundles||[]).filter((b:any)=>b.rootBundleId!==bundleId);bundles.push({rootBundleId:bundleId,bundleIds:[bundleId],bundleNames:[bundle.name],loadedAt:now()});receipt.bundles=bundles;await saveContext(identity,workspaceId,recalc(receipt));return {bundle,loaded,receipt};}
export async function unloadBundle(identity:RuntimeIdentity,workspaceId:string,bundleId:string){const receipt=await contextRow(identity,workspaceId)||blankReceipt(workspaceId,identity.clientId);receipt.files=(receipt.files||[]).filter((f:any)=>String(f.bundleId||'')!==bundleId);receipt.bundles=(receipt.bundles||[]).filter((b:any)=>b.rootBundleId!==bundleId && !(b.bundleIds||[]).includes(bundleId));return saveContext(identity,workspaceId,recalc(receipt));}

async function profileRole(identity:RuntimeIdentity,workspaceId:string){await requireMcpWorkspace(identity.user,workspaceId);return identity.user.role==='owner'||identity.user.role==='admin'?'owner':((await visibleWorkspaces(identity.user)).find((w:any)=>w.id===workspaceId)?.permission||'viewer');}
export async function listProfiles(identity:RuntimeIdentity,workspaceId:string){const role=await profileRole(identity,workspaceId);return profileCatalog(workspaceId,role,identity.user.id,identity.user.role);}
export async function viewProfile(identity:RuntimeIdentity,workspaceId:string,reference:string){const role=await profileRole(identity,workspaceId),catalog=await profileCatalog(workspaceId,role,identity.user.id,identity.user.role),raw=String(reference||'').trim(),pathId=raw.replace(/^Profiles\//i,'');const profile=(catalog.profiles||[]).find((p:any)=>String(p.id)===raw||String(p.id)===pathId||String(p.name||'').toLowerCase()===raw.toLowerCase()||String(p.name||'').toLowerCase()===pathId.toLowerCase());if(!profile)throw Object.assign(new Error('Profile is unavailable or access is denied'),{status:404,code:'PROFILE_NOT_FOUND'});const projection=await profileKnowledgeProjection(workspaceId,profile.id,role,identity.user.id,identity.user.role),body=JSON.stringify(projection.profile,null,2);return {profile:projection.profile,profileText:body,displayText:body,characters:body.length,source:'workspace-profile'};}
export async function saveProfileChanges(identity:RuntimeIdentity,workspaceId:string,profileId:string,changes:any){const role=await profileRole(identity,workspaceId);if(!changes||typeof changes!=='object'||Array.isArray(changes))throw Object.assign(new Error('Profile changes must be an object'),{status:400});const profile=await updateProfile(workspaceId,profileId,changes,identity.user.username,role,identity.user.id),projection=await profileKnowledgeProjection(workspaceId,profileId,role,identity.user.id,identity.user.role),body=JSON.stringify(projection.profile,null,2),receipt=await contextRow(identity,workspaceId);if(receipt){for(const item of receipt.files||[]){if(item.source==='profile'&&String(item.profileId||'')===profileId){item.profileName=profile.name;item.characters=body.length;item.loadedAt=now();}}await saveContext(identity,workspaceId,recalc(receipt));}return {profile:projection.profile,profileText:body,displayText:body,characters:body.length,activeContext:receipt?recalc(receipt):null};}
export async function loadProfile(identity:RuntimeIdentity,workspaceId:string,profileId:string,detail='standard',meta:any={}){const role=await profileRole(identity,workspaceId);const projection=await profileKnowledgeProjection(workspaceId,profileId,role,identity.user.id,identity.user.role);const profile=projection.profile;const body=detail==='summary'?JSON.stringify({name:profile.name,type:profile.type,status:profile.status,fields:profile.fields},null,2):JSON.stringify(profile,null,2);const item={path:`Profiles/${profileId}`,profileId,profileName:profile.name,source:'profile',bundleId:meta.bundleId||null,bundleName:meta.bundleName||null,characters:body.length,loadedAt:now()};const receipt=await appendItems(identity,workspaceId,[item]);return {profile,item,receipt,content:body};}

export async function workspaceUiState(identity:RuntimeIdentity,workspaceId='default',strength?:string,projectId?:string|null){const workspaces=await visibleWorkspaces(identity.user);const workspace=workspaceId==='default'?(workspaces.find((w:any)=>w.is_main)||workspaces[0]):workspaces.find((w:any)=>w.id===workspaceId);if(!workspace)throw Object.assign(new Error('Workspace access denied'),{status:403});const [startup,projects,bundles,profiles,libraryItems,presets,metadata,assigned,active]=await Promise.all([getStartup(workspace.id),listMcpProjects(workspace.id),listContextBundles(workspace.id),listProfiles(identity,workspace.id),listLibraryItems(identity,workspace.id),getPresets(workspace.id,projectId||null),getPresetMetadata(workspace.id,projectId||null),getPresetBundles(workspace.id,projectId||null),activeContext(identity,workspace.id)]);const chosen=strength||null;const preset=chosen?presets?.[chosen]||{}:{};const config={...startup,projects,project:projectId?projects.find((p:any)=>p.id===projectId)||null:null,presetMetadata:metadata,presetItems:preset.items||[],presetProfileIds:preset.profileIds||[],presetProfileBundleIds:preset.profileBundleIds||[],assignedBundles:chosen?assigned?.[chosen]||[]:[],startupSelection:{defaultItems:startup.defaultItems||[],presetItems:preset.items||[],assignedContextBundles:chosen?assigned?.[chosen]||[]:[]}};return {workspaceId:workspace.id,workspaces,config,projectId:projectId||null,dashboard:{user:{username:identity.user.username,displayName:identity.user.display_name,systemRole:identity.user.role},workspace:{id:workspace.id,name:workspace.name,status:workspace.status,role:workspace.permission},alerts:[]},activeContext:active,activeFiles:active?.files||[],changeStatus:{outdated:false,changedFiles:[]},profiles:profiles.profiles||[],profileBundles:profiles.profileBundles||[],libraryItems,settings:profiles.settings||{},permissions:profiles.permissions||{},slots:{master:null,additional:null},bundles,canWrite:workspace.permission!=='viewer'};}

export async function loadDefaults(identity:RuntimeIdentity,workspaceId:string,projectId?:string|null){const startup=await getStartup(workspaceId);for(const item of startup.defaultItems||[]){if(item.type==='folder')await loadFolder(identity,workspaceId,item.path,100,1000000);else await loadFile(identity,workspaceId,item.path,{source:'default'});}for(const id of startup.defaultProfileIds||[])await loadProfile(identity,workspaceId,id,'standard').catch(()=>{});const receipt=await activeContext(identity,workspaceId);return {receipt};}
export async function runStartup(identity:RuntimeIdentity,workspaceId:string,strength:string,projectId?:string|null){const startup=await getStartup(workspaceId);const presets=await getPresets(workspaceId,projectId||null);const assignments=await getPresetBundles(workspaceId,projectId||null);await clearActiveContext(identity,workspaceId);await loadDefaults(identity,workspaceId,projectId);const preset=presets?.[strength]||{};for(const item of preset.items||[]){const path=item.path||item.item_path;if(!path)continue;if((item.type||item.item_type)==='folder'||item.recursive)await loadFolder(identity,workspaceId,path,100,2000000);else await loadFile(identity,workspaceId,path,{source:'preset'});}for(const id of preset.profileIds||[])await loadProfile(identity,workspaceId,id,'standard').catch(()=>{});for(const b of assignments?.[strength]||[])await loadBundle(identity,workspaceId,b.bundleId);const receipt=await activeContext(identity,workspaceId)||blankReceipt(workspaceId,identity.clientId);receipt.preset=strength;receipt.strength=strength;receipt.projectId=projectId||null;return {receipt:await saveContext(identity,workspaceId,recalc(receipt))};}
export async function writeFile(identity:RuntimeIdentity,workspaceId:string,path:string,data:string,encoding='text'){await requireMcpWorkspace(identity.user,workspaceId);await requireCapability(identity.user,workspaceId,path,'write');const bytes=encoding==='base64'?Buffer.from(data,'base64'):Buffer.from(data,'utf8');const entry=await writeFileBytes({workspaceId,path,bytes,userId:identity.user.id,preferText:encoding!=='base64',upsert:true});return {path:entry.path,bytes:bytes.length,mimeType:entry.mime_type};}
export async function makeFolder(identity:RuntimeIdentity,workspaceId:string,path:string){await requireMcpWorkspace(identity.user,workspaceId);await requireCapability(identity.user,workspaceId,path,'create');return createFolder(workspaceId,path,identity.user.id);}
export async function moveWorkspaceEntry(identity:RuntimeIdentity,workspaceId:string,sourcePath:string,destinationPath:string){await requireMcpWorkspace(identity.user,workspaceId);await requireCapability(identity.user,workspaceId,sourcePath,'move');await moveEntry(workspaceId,sourcePath,destinationPath);return {sourcePath,destinationPath};}
export async function deleteWorkspaceEntry(identity:RuntimeIdentity,workspaceId:string,path:string){await requireMcpWorkspace(identity.user,workspaceId);await requireCapability(identity.user,workspaceId,path,'delete');await purgeEntry(workspaceId,path);return {path,deleted:true};}
export async function uploadFromUrl(identity:RuntimeIdentity,workspaceId:string,directory:string,file:any){const url=String(file?.download_url||file?.downloadUrl||'');if(!/^https:\/\//i.test(url))throw new Error('A secure ChatGPT file download URL is required');const response=await fetch(url);if(!response.ok)throw new Error(`ChatGPT file download failed (${response.status})`);const name=String(file?.file_name||file?.fileName||file?.name||'upload.bin').replace(/[\\/:*?"<>|]/g,'_');const path=normalizePath([directory,name].filter(Boolean).join('/'));await requireCapability(identity.user,workspaceId,path,'write');const bytes=Buffer.from(await response.arrayBuffer());const entry=await writeFileBytes({workspaceId,path,bytes,mimeType:file?.mime_type||file?.mimeType||response.headers.get('content-type'),userId:identity.user.id,preferText:false,upsert:false});return {path:entry.path,bytes:bytes.length};}
